# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "msc-master" do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end

    master.vm.network "private_network", ip: "192.168.0.2"

    # forward rabbit management to 8080 port
    master.vm.network "forwarded_port", guest: 8080, host: 8080

    master.vm.hostname = "msc-master"

    master.vm.provision "shell", path: "bootstrap_common.sh"
    master.vm.provision "shell", path: "bootstrap_master.sh"
  end
end
