# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "msc-devbox" do |master|
    master.vm.box = "ubuntu/trusty64"
    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end

    master.vm.hostname = "msc-master"

    master.vm.provision "shell", path: "bootstrap_common.sh"
  end
end
